### ISSUE TITLE
Using phpadd with Zend

### ISSUE THREAD

**Issue by adrianmester** [fmntf/phpadd#1]
Zend Framework has a namespace autoloader that allows you to load you classes using something like this:

Let's say you have a directory structure like this:

```
index.php
MyStuff/
  |- SomeClass.php (contains the class MyStuff_SomeClass)
  |- AnotherClass.php (contains the class MyStuff_AnotherClass)
```

In index.php I can use the following snippet:

```
$autoloader = Zend_Loader_Autoloader::getInstance();
$autoloader->registerNamespace('MyStuff_');

$obj = new MyStuff_SomeClass();
```

When running phpadd on a project I got:

```
PHP Fatal error:  Class 'Page_View' not found in /controllers/mobile/PageController.php on line 18
```

Is there any way around this?

**Comment by fmntf** [comment]
I use Zend Framework and I tested phpadd over it.
You just need to use the "--bootstrap file.php" switch while running phpadd.

You should derivate your "file.php" from your Zend's index/bootstrap registering all the namespaces you need. Or you may just need something like this: http://pastie.org/1387068

**Comment by adrianmester** [comment]
Thanks, I'll give it a try
