### ISSUE TITLE
Extensive Notices

### ISSUE THREAD

**Issue by grahamc** [fmntf/phpadd#3]
When running PHPADD against my symfony project I get extensive PHP notices:

$ php build/phpadd/phpadd.php --publish-html cache/build/phpadd.html --bootstrap test/bootstrap.php lib/

PHP Notice:  Undefined offset: 1 in /Users/gchristensen/Sites/app/build/phpadd/PHPADD/Parser.php on line 124
PHP Stack trace:
PHP   1. {main}() /Users/gchristensen/Sites/app/build/phpadd/phpadd.php:0
PHP   2. PHPADD_Cli->run() /Users/gchristensen/Sites/app/build/phpadd/phpadd.php:32
PHP   3. PHPADD_Detector->getMess($path = 'lib/') /Users/gchristensen/Sites/app/build/phpadd/PHPADD/Cli.php:68
PHP   4. PHPADD_Detector->analyze($className = 'FieldGroup') /Users/gchristensen/Sites/app/build/phpadd/PHPADD/Detector.php:54
PHP   5. PHPADD_Parser->analyze($classname = 'FieldGroup', $filter = class PHPADD_Filter { private $scanProtected = TRUE; private $scanPrivate = TRUE }) /Users/gchristensen/Sites/app/build/phpadd/PHPADD/Detector.php:67
PHP   6. PHPADD_Parser->validateDocBlock($method = class ReflectionMethod { public $name = 'getUserIdParent'; public $class = 'FieldGroup' }) /Users/gchristensen/Sites/app/build/phpadd/PHPADD/Parser.php:63
PHP   7. PHPADD_Parser->getDocBlockParams($method = class ReflectionMethod { public $name = 'getUserIdParent'; public $class = 'FieldGroup' }) /Users/gchristensen/Sites/app/build/phpadd/PHPADD/Parser.php:148

**Comment by grahamc** [comment]
Turns out that a docblock of the following format 
    /**
     \* Some desc here
     *
     \* @param $rank
     \* @return ReportMetricFormat $report_metric_format
     */
    public static function retrieveByRank($rank = 1) {

will cause these errors. See pull request #7

**Comment by fmntf** [comment]
Fixed with your patch on branch bug-3. Will merge in master for next release.
