### ISSUE TITLE
Actually Executing Methods?

### ISSUE THREAD

**Issue by grahamc** [fmntf/phpadd#5]
PHPADD appears to actually be executing methods. Is this possible? For example, the Facebook PHP SDK has a method:
  protected function getCurrentUrl() {
    $protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on'
      ? 'https://'
      : 'http://';
    $currentUrl = $protocol . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
    $parts = parse_url($currentUrl);

```
// drop known fb params
$query = '';
if (!empty($parts['query'])) {
  $params = array();
  parse_str($parts['query'], $params);
  foreach(self::$DROP_QUERY_PARAMS as $key) {
    unset($params[$key]);
  }
  if (!empty($params)) {
    $query = '?' . http_build_query($params, null, '&');
  }
}

// use port if non default
$port =
  isset($parts['port']) &&
  (($protocol === 'http://' && $parts['port'] !== 80) ||
   ($protocol === 'https://' && $parts['port'] !== 443))
  ? ':' . $parts['port'] : '';

// rebuild
return $protocol . $parts['host'] . $port . $parts['path'] . $query;
```

  }

which causes PHPADD to go nuts, as it isn't being executed through a webserver:

Notice: Undefined index: REQUEST_URI in /Users/gchristensen/Sites/app/lib/vendor/facebook/php-sdk/src/facebook.php on line 823

Call Stack:
    0.0004     628480   1. {main}() /Users/gchristensen/Sites/app/build/phpadd/phpadd.php:0
    0.0033     910088   2. PHPADD_Cli->run() /Users/gchristensen/Sites/app/build/phpadd/phpadd.php:32
    0.5182   14024480   3. PHPADD_Detector->getMess(string(4)) /Users/gchristensen/Sites/app/build/phpadd/PHPADD/Cli.php:68
   13.8669  136160512   4. require_once('/Users/gchristensen/Sites/app/lib/vendor/facebook/php-sdk/examples/example.php') /Users/gchristensen/Sites/app/build/phpadd/PHPADD/Detector.php:52
   13.8685  136400848   5. Facebook->getLoginUrl(???) /Users/gchristensen/Sites/app/lib/vendor/facebook/php-sdk/examples/example.php:36
   13.8685  136401064   6. Facebook->getCurrentUrl() /Users/gchristensen/Sites/app/lib/vendor/facebook/php-sdk/src/facebook.php:370

Is there something I'm missing or a way to keep this from occurring?

**Comment by fmntf** [comment]
PHPADD includes files since Reflection needs the classes to be loaded (it's not possible to tell Reflection "get that class which is in that file".

If a file has something different from class definition, the instructions will be executed as any other normal included.

I file like that
<code>class A
{
   public function f(){ ... }
}

$obj = new A();
$obj->f();</code>

will execute A::f() and I do not think that is possible to prevent that.
I file that contains classes should not contain something else.

**Comment by grahamc** [comment]
This makes sense. I've removed the example due to how blatantly dumb it was being.

Thank you!
