### ISSUE TITLE
Does not exit(1) upon a failure or error

### ISSUE THREAD

**Issue by grahamc** [fmntf/phpadd#6]
having PHPADD exit(1) would allow me to easily implement this into my regular unit testing schedule, which would be very helpful.

Error validating application.
Usage: phpadd [options] /directory/to/scan

Options:
   --skip-protected    skips the scanning of protected methods
   --skip-private      skips the scanning of private methods
   --bootstrap file    includes `file` before the scan

At least one publisher must be given: 
   --publish-html <file>     HTML output
   --publish-xml  <file>     XML output
   --publish-delim <file>    Tab delimited output

Exit: 0

**Comment by fmntf** [comment]
Done in 6565a7be31b3833cd7e3cc2a04af66248d9fc81d.
Will be in next release.
